library(dplyr)
source(here::here("R/gt_formatter.R"))
df_awesome <-
  tibble::tribble(
    ~title, ~authors, ~url, ~resource_type, ~level, ~note, ~pickup,
    "Machine Learning with tidymodels", c("Julia Silge", "Max Kuhn", "David Robinson"), "https://workshops.tidymodels.org", "course", "beginner", NA_character_, TRUE,
    "Create machine learning models with R and tidymodels",
    "Microsoft", "https://docs.microsoft.com/en-us/learn/paths/machine-learning-with-r/", 
    "course", "beginner", NA_character_, TRUE,
    "Feature Engineering and Selection: A Practical Approach for Predictive Models", 
    c("Max Kuhn", "Kjell Johnson"), "http://www.feat.engineering", 
    "book", "general", NA_character_, TRUE,
    "tidy-apm", 
    "Max Kuhn", "https://github.com/topepo/tidy-apm",
    "book", "advanced", "a tidymodels companion for the 2013 book 'Applied Predictive Modeling'", FALSE,
    "ISLR tidymodels Labs",
    "Emil Hvitfeldt", "https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/index.html", 
    "book", "advanced", "A version of 'An Introduction to Statistical Learning' book with the content of the book replaced by the process in tidymodels", FALSE,
    "Supervised Machine Learning for Text Analysis in R",
    c("Emil Hvitfeldt", "Julia Silge"), "https://smltar.com/", 
    "book", "advanced", NA_character_, TRUE,
    "Tidy Modeling with R", 
    c("Max Kuhn", "Julia Silge"), "https://www.tmwr.org", 
    "book", "general", NA_character_, TRUE,
    "Tidy your mental models", 
    "Alison Hill", "https://apreshill.github.io/tidy-mental-models/", 
    "slide", "beginner", NA_character_, TRUE,
    "Hands-On Machine Learning with R",
    c("Bradley Boehmke", "Brandon Greenwell"), "https://bradleyboehmke.github.io/HOML/",
    "book", "beginner", NA_character_, FALSE,
    "Get started with tidymodels and #TidyTuesday Palmer penguins",
    "Julia Silge", "https://juliasilge.com/blog/palmer-penguins/",
    "post", "beginner", NA_character_, FALSE,
    "Tidymodels: tidy machine learning in R",
    "Rebecca Barter", "https://www.rebeccabarter.com/blog/2020-03-25_machine_learning/",
    "post", "advanced", NA_character_, FALSE,
    "Catching up with the tidymodels",
    "Ringa_hyj", "https://speakerdeck.com/ringa_hyj/catching-up-with-the-tidymodels-dot-japan-dot-r-2021-lt",
    "slide", "beginner", NA_character_, FALSE,
    "Practical Data Science with R and Python",
    "Shinya Uryu", "https://uribo.github.io/practical-ds/",
    "book", "beginner", NA_character_, FALSE,
    "Data Preprocessing Cookbook",
    "Shinya Uryu", "https://uribo.github.io/dpp-cookbook/",
    "course", "beginner", NA_character_, FALSE,
    "tidymodelsによるtidyな機械学習（その3：ハイパーパラメータのチューニング）",
    "森下 光之助", "https://dropout009.hatenablog.com/entry/2019/11/10/125650", 
    "post", "advanced", NA_character_, FALSE,
    "Tidymodels DVC Mashup",
    "Sean Lopp", "https://loppsided.blog/posts/2020-10-26-tidymodels-dvc-mashup/",
    "post", "advanced", NA_character_, FALSE,
    "Classification with Tidymodels, Workflows and Recipes",
    "Jan Kirenz", "https://www.kirenz.com/post/2021-02-17-r-classification-tidymodels/",
    "post", "beginner", NA_character_, FALSE,
    "tidymodelsで覚えるRでのモデル構築と運用",
    "Shinya Uryu", "https://speakerdeck.com/s_uryu/tidymodels2020",
    "slide", "beginner", NA_character_, FALSE)

# df_awesome <- 
#   df_awesome |> 
#   tidyr::pack(labels = c(type, level))

df_users <-
  tibble::tribble(
    ~name, ~twitter, ~github,
    "Emil Hvitfeldt", "Emil_Hvitfeldt", "EmilHvitfeldt",
    "Kjell Johnson", NA_character_, NA_character_,
    "Max Kuhn", "topepos", "topepo",
    "David Robinson", "drob", "dgrtwo",
    "Julia Silge", "juliasilge", "juliasilge",
    "Alison Hill", "apreshill", "apreshill",
    "Ringa_hyj", "Ringa_hyj", "amazongodman",
    "Sean Lopp", "lopp_sean", "slopp",
    "Jan Kirenz", NA_character_, "kirenz",
    "Bradley Boehmke", "bradleyboehmke", "bradleyboehmke",
    "Brandon Greenwell", "bgreenwell8", "bgreenwell",
    "Rebecca Barter", "rlbarter", "rlbarter",
    "Shinya Uryu", "u_ribo", "uribo",
    "森下 光之助", "dropout009", "dropout009")
